### ISSUE TITLE
Restricted-access example has multiple errors

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algorand-builder#245]
- The bob account should be slightly fund to opt-in for the asset
- In the teal, pragma version must be on the first line

**Comment by ratik21** [comment]
This was recently added. We are currently updating the example project.

**Comment by Lumene98** [comment]
> 
> 
> This was recently added. We are currently updating the example project.

Oh ok thank you

**Comment by ratik21** [comment]
> The types for the 'Updating asset clawback to escrow' should be updated because it doesn't let me build at the current state

@Lumene98 for this point, did you mean the types for `scTmplParams` (the other issue you created)? Or do you mean something else? I am assuming you're doing this in a `typescript` project (as this one is `js` and doesn't require build).

**Comment by Lumene98** [comment]
> 
> 
> > The types for the 'Updating asset clawback to escrow' should be updated because it doesn't let me build at the current state
> 
> @Lumene98 for this point, did you mean the types for `scTmplParams` (the other issue you created)? Or do you mean something else? I am assuming you're doing this in a `typescript` project (as this one is `js` and doesn't require build).

I mean something else: this is for the execParams of executeTransaction

**Comment by ratik21** [comment]
@Lumene98 i have converted the file to `typescript` and it seems fine to me. You're probably having an issue with converting `JS` to `TS`. The only type error i see is with `scTmplParams` (which will be fixed soon). You can check `/examples/htlc-pyteal-ts` for reference for conversion to ts. 
TIP: For conversion to TS, you'll need to check for `undefined` behaviour (proceed while verifying that data is defined, otherwise you'll get a typeError). Also for `execParams`, you'll need to have the transferParam type as well. Eg.
```
const assetConfigParams: rtypes.ModifyAssetParam = { // passed type here
  type: rtypes.TransactionType.ModifyAsset,
  sign: rtypes.SignType.SecretKey,
  fromAccount: creator,
  assetID: assetInfo.assetIndex,
  fields: assetModFields,
  payFlags: { totalFee: 1000 }
};
await executeTransaction(deployer, assetConfigParams);
```
If you still face an issue, please let me know and i'll help you to convert the file to TS.

**Comment by Lumene98** [comment]
> : rtypes.ModifyAssetParam

Yes sorry, I realized I forgot to add the type there my bad on this one
