### ISSUE TITLE
Connection Error to the js-algorand-sdk package

### ISSUE THREAD

**Issue by Mine77** [scale-it/algorand-builder#83]
Hi, I got this error when trying to run `yarn add algob`

```
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://raw.githubusercontent.com/algorand/js-algorand-sdk/3999aa43fc3d945b38419339c593bb5fd72e49c6/package.json: connect ECONNREFUSED 0.0.0.0:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/haichaozhu/code/algob-project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I figured this might be a connection problem of my network. (I'm in China and I'm using a local mirror site for all yarn and npm packages).
However I don't have problems installing algorand js SDK alone.

Not an expert in js coding. So could be a silly question.

**Comment by robert-zaremba** [comment]
Could be because the HTTPS connection is blocked. 

Can you do this, please

```
mkdir test-algob
cd test-algob
yarn init
yarn add algob
```

I've just did it and it worked.
If this doesn't work then try to run (no need to repeat other steps):
```
npm install algob
```
Please let me know if this works.

**Comment by Invertisment** [comment]
If you have a local mirror site you should somehow make sure that it came from our repository and that it's compiled correctly.
This is what I have in my `yarn.lock` after a successful install:
```
algob@^0.0.3:
  version "0.0.3"
  resolved "https://registry.yarnpkg.com/algob/-/algob-0.0.3.tgz#6ea5f46463ffb183e443b10ccca9c7a7ad79d243"
  integrity sha512-g9uKdoi5SmHh9ujBeNn92ao/wHymibiWc785UvbClp40769aiawBeZHyaUIVzG/m/3mI9K9izLsr8C06Hilvhg==
  dependencies:
    algosdk "github:algorand/js-algorand-sdk#v1.7.0-beta"
...
```

And if I go to `https://registry.yarnpkg.com/algob` then I can find a link to our github repository:
`git+https://github.com/scale-it/algorand-builder.git`

I don't know which version is deployed to `https://www.npmjs.com/package/algob/v/0.0.3` but it has to be a commit of a master branch. 

--------

If none of this suggests a solution then you can compile `algob` by hand and do `yarn link` to have it locally.
We currently don't have a way to import directly from github because we have a monorepo project (this would be a way to not have a npmjs package this early).

To run a linked package with yarn you can do this (assuming you use unix-like terminal):
```
git clone https://github.com/scale-it/algorand-builder/
cd algorand-builder/packages/algob
yarn build
yarn link
```
Then go to your project, and execute `yarn link algob`

This will add a link in your project (not exactly this way but it works similarly to this):
`project/node_modules/algob` -> `~/.../algorand-builder/packages/algob/build/`

Then if you have your local yarn `bin/` directory in `$PATH` you'll be able to even use the CLI tool (as you would regularly):
`$> algob -h`

**Comment by Mine77** [comment]
Thanks. I'll give it a try.
Since it's my own problem then it's ok.
Let me try to figure it out myself.
Feel free to close the issue.

**Comment by robert-zaremba** [comment]
Let's keep it open to see if this worked or not.

**Comment by robert-zaremba** [comment]
BTW - in the master branch we did some breaking changes and checking now with the example.
